language: ruby

before_install: gem install bundler -v 1.17.3
script: bundle exec rake test

rvm:
  - 2.2.6
  - 2.3.3
  - 2.6.1

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
